////
This file is generated! See scripts/changelog.py
////

[[release-notes-5.0.0-alpha3]]
=== Beats version 5.0.0-alpha3
2016-05-31 https://github.com/elastic/beats/compare/v5.0.0-alpha2...v5.0.0-alpha3[View commits]

==== Filebeat


*Breaking*

- Stop following symlink. Symlinks are now ignored.
  https://github.com/elastic/beats/issues/1686[1686]
- The state for files which fall under ignore_older is not stored anymore. This has the consequence, that if a file which fell under ignore_older is updated, the whole file will be crawled.


*Added*

- The registry format was changed to an array instead of dict. The migration to the new format will happen automatically at the first startup.  https://github.com/elastic/beats/issues/1703[1703]

==== Libbeat


*Deprecated*

- The support for doing GeoIP lookups is deprecated and will be removed in version 6.0.
  https://github.com/elastic/beats/issues/1601[1601]

*Breaking*

- All configuration settings under `shipper:` are moved to be top level configuration settings. I.e.
  `shipper.name:` becomes `name:` in the configuration file.
  https://github.com/elastic/beats/issues/1570[1570]

*Added*

- Add conditions to generic filtering.
  https://github.com/elastic/beats/issues/1623[1623]

==== Beats


==== Metricbeat


*Added*

- First public release, containing the following modules: apache, mysql, nginx, redis, system, and zookeeper.


==== Winlogbeat


*Breaking*

- All configuration settings under `shipper:` are moved to be top level configuration settings. I.e. `shipper.name:` becomes `name:` in the configuration file.  https://github.com/elastic/beats/issues/1570[1570]

==== Packetbeat


*Bug*

- Add missing nil-check to memcached GapInStream handler.
  https://github.com/elastic/beats/issues/1162[1162]

[[release-notes-5.0.0-alpha2]]
=== Beats version 5.0.0-alpha2
2016-05-03 https://github.com/elastic/beats/compare/v5.0.0-alpha1...v5.0.0-alpha2[View commits]

==== Filebeat


*Breaking*

- Default location for the registry file was changed to be `data/registry` from the binary directory,
  rather than `.filebeat` in the current working directory. This affects installations for zip/tar.gz/source,
  the location for DEB and RPM packages stays the same.
  https://github.com/elastic/beats/issues/1373[1373]

*Bug*

- Improvements in registrar dealing with file rotation.
  https://github.com/elastic/beats/issues/1281[1281]
- Fix issue with JSON decoding where `@timestamp` or `type` keys with the wrong type could cause Filebeat
  to crash.
  https://github.com/elastic/beats/issues/1378[1378]
- Fix issue with JSON decoding where values having `null` as values could crash Filebeat.
  https://github.com/elastic/beats/issues/1466[1466]
- Multiline reader normalizing newline to use `\n`.
  https://github.com/elastic/beats/issues/1552[1552]

==== Libbeat


*Breaking*

- On DEB/RPM installations, the binary files are now found under `/usr/share/{{beat_name}}/bin`, not in `/usr/bin`.
  https://github.com/elastic/beats/issues/1601[1601]
- The logs are written by default to self rotating files, instead of syslog.
  https://github.com/elastic/beats/issues/1371[1371]
- Remove deprecated `host` option from elasticsearch, logstash and redis outputs.
  https://github.com/elastic/beats/issues/1474[1474]

*Bug*

- Reset backoff factor on partial ACK.
  https://github.com/elastic/beats/issues/1803[1803]
- Fix beats load balancer deadlock if max_retries: -1 or publish_async is enabled in filebeat.
  https://github.com/elastic/beats/issues/1829[1829]
- Drain response buffers when pipelining is used by Redis output.
  https://github.com/elastic/beats/issues/1353[1353]
- Unterminated environment variable expressions in config files will now cause an error.
  https://github.com/elastic/beats/issues/1389[1389]
- Fix issue with the automatic template loading when Elasticsearch is not available on Beat start.
  https://github.com/elastic/beats/issues/1321[1321]
- Fix bug affecting -cpuprofile, -memprofile, and -httpprof CLI flags.
  https://github.com/elastic/beats/issues/1415[1415]
- Fix race when multiple outputs access the same event with logstash output manipulating event.
  https://github.com/elastic/beats/issues/1410[1410]
- Seed random number generator using crypto.rand package.
  https://github.com/elastic/beats/issues/1503[1503]
- Fix beats hanging in -configtest
  https://github.com/elastic/beats/issues/1213[1213]
- Fix kafka log message output
  https://github.com/elastic/beats/issues/1516[1516]

*Added*

- Add support for TLS to Redis output.
  https://github.com/elastic/beats/issues/1353[1353]
- Add SOCKS5 proxy support to Redis output.
  https://github.com/elastic/beats/issues/1353[1353]
- Failover and load balancing support in redis output.
  https://github.com/elastic/beats/issues/1353[1353]
- Multiple-worker per host support for redis output.
  https://github.com/elastic/beats/issues/1353[1353]
- Added ability to escape `${x}` in config files to avoid environment variable expansion.
  https://github.com/elastic/beats/issues/1389[1389]
- Configuration options and CLI flags for setting the home, data and config paths.
  https://github.com/elastic/beats/issues/1373[1373]
- Configuration options and CLI flags for setting the default logs path.
  https://github.com/elastic/beats/issues/1437[1437]
- Update to Go 1.6.2
  https://github.com/elastic/beats/issues/1447[1447]
- Add Elasticsearch template files compatible with Elasticsearch 2.x.
  https://github.com/elastic/beats/issues/1501[1501]
- Add scripts for managing the dashboards of a single Beat.
  https://github.com/elastic/beats/issues/1359[1359]

==== Topbeat


==== Beat-Generator


*Added*

- Add dev-tools/packer to package the beat for all supported platforms


*Changed*

- The registry format was changed to an array instead of dict. The migration to the new format will happen automatically at the first startup.
- Use ucfg.Unpack() instead of cfgfile.Read() in Beater.Config method.
- Rename `Configuration` variable in beat struct to `beatConfig` as generalization from @buehler.
- Update Golang dependency to 1.6.0

==== Metricbeat


*Bug*

- Fix the CPU values returned for each core.
  https://github.com/elastic/beats/issues/1863[1863]

==== Packetbeat


*Breaking*

- Configuration of redis topology support changed.
  https://github.com/elastic/beats/issues/1353[1353]
- Move all Packetbeat configuration options under the packetbeat namespace.
  https://github.com/elastic/beats/issues/1417[1417]

*Added*

- Fix compile issues for OpenBSD.
  https://github.com/elastic/beats/issues/1347[1347]

